capp/calculator/forms.py
from flask_wtf import FlaskForm
from wtforms import  SubmitField,  SelectField,  FloatField
from wtforms.validators import InputRequired

class BusForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
  choices=[('Diesel', 'Diesel')])
  submit = SubmitField('Submit')

class CarForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
  choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')])
  submit = SubmitField('Submit')  

class PlaneForm(FlaskForm):
    kms = FloatField('Kilometers', [InputRequired()])
    fuel_type = SelectField('Flight Class', [InputRequired()],
    choices=[('Economy', 'Economy'), ('Business', 'Business')])
    submit = SubmitField('Submit')

class FerryForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Transport class', [InputRequired()], 
  choices=[('Passenger with car', 'Passenger with car'), ('Passenger only', 'Passenger only')])
  submit = SubmitField('Submit')

class TrainForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Diesel', 'Diesel'), ('Electric', 'Electric')])
  submit = SubmitField('Submit')

class WalkForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('No Fossil Fuel', 'No Fossil Fuel')])
  submit = SubmitField('Submit')  

capp/calculator/__init__.py
#

capp/calculator/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, flash
from capp.models import Transport
from capp import db
from datetime import timedelta, datetime
from flask_login import login_required, current_user
from capp.calculator.forms import BusForm, CarForm, PlaneForm, FerryForm, TrainForm, WalkForm
import json
calculator = Blueprint('calculator', __name__)
# Emissions factor per transport in kg per passenger km
# Data from: 
efco2 = {
    'Bus': {'Diesel': 0.030},
    'Car': {'Petrol': 0.198, 'Diesel': 0.229, 'Electric': 0.059},
    'Plane': {'Economy': 0.127, 'Business': 0.284},
    'Ferry': {'Passenger with car': 0.563, 'Passenger only': 0.186},
    'Train': {'Diesel': 0.091, 'Electric': 0.007},
    'Walk': {'No Fossil Fuel': 0}
}
# Carbon app, main page
@calculator.route('/calculator')
@login_required
def calculator_home():
    return render_template('calculator/calculator_home.html', title='calculator')
# Carbon app, plane
@calculator.route('/calculator/new_entry_plane', methods=['GET', 'POST'])
@login_required
def new_entry_plane():
    form = PlaneForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Plane'
        co2 = float(kms) * efco2[transport][fuel]
        co2 = float("{:.2f}".format(co2))
        emissions = Transport(
            kms=kms,
            transport=transport,
            fuel=fuel,
            co2=co2,
            author=current_user
        )
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template(
        'calculator/new_entry_plane.html',
        title='Plane Calculator',
        form=form
    )
# Carbon app, walk
@calculator.route('/calculator/new_entry_walk', methods=['GET', 'POST'])
@login_required
def new_entry_walk():
    form = WalkForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Walk'
        co2 = float(kms) * efco2[transport][fuel]
        co2 = float("{:.2f}".format(co2))
        emissions = Transport(
            kms=kms,
            transport=transport,
            fuel=fuel,
            co2=co2,
            author=current_user
        )
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template(
        'calculator/new_entry_walk.html',
        title='Walk/Bike Calculator',
        form=form
    )
# Carbon app, bus
@calculator.route('/calculator/new_entry_bus', methods=['GET', 'POST'])
@login_required
def new_entry_bus():
    form = BusForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Bus'
        co2 = float(kms) * efco2[transport][fuel]
        co2 = float("{:.2f}".format(co2))
        emissions = Transport(
            kms=kms,
            transport=transport,
            fuel=fuel,
            co2=co2,
            author=current_user
        )
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template(
        'calculator/new_entry_bus.html',
        title='Bus Calculator',
        form=form
    )
# Carbon app, car
@calculator.route('/calculator/new_entry_car', methods=['GET', 'POST'])
@login_required
def new_entry_car():
    form = CarForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Car'
        co2 = float(kms) * efco2[transport][fuel]
        co2 = float("{:.2f}".format(co2))
        emissions = Transport(
            kms=kms,
            transport=transport,
            fuel=fuel,
            co2=co2,
            author=current_user
        )
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template(
        'calculator/new_entry_car.html',
        title='Car Calculator',
        form=form
    )
# Carbon app, ferry
@calculator.route('/calculator/new_entry_ferry', methods=['GET', 'POST'])
@login_required
def new_entry_ferry():
    form = FerryForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Ferry'
        co2 = float(kms) * efco2[transport][fuel]
        co2 = float("{:.2f}".format(co2))
        emissions = Transport(
            kms=kms,
            transport=transport,
            fuel=fuel,
            co2=co2,
            author=current_user
        )
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template(
        'calculator/new_entry_ferry.html',
        title='Ferry Calculator',
        form=form
    )
# Carbon app, train
@calculator.route('/calculator/new_entry_train', methods=['GET', 'POST'])
@login_required
def new_entry_train():
    form = TrainForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Train'
        co2 = float(kms) * efco2[transport][fuel]
        co2 = float("{:.2f}".format(co2))
        emissions = Transport(
            kms=kms,
            transport=transport,
            fuel=fuel,
            co2=co2,
            author=current_user
        )
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template(
        'calculator/new_entry_train.html',
        title='Train Calculator',
        form=form
    )
# Your data
@calculator.route('/calculator/your_data')
@login_required
def your_data():
    # Table
    entries = Transport.query.filter_by(author=current_user).\
        filter(Transport.date > (datetime.now() - timedelta(days=5))).\
        order_by(Transport.date.desc()).order_by(Transport.transport.asc()).all()
    
    # Kilometers by category
    kms_by_transport = db.session.query(db.func.sum(Transport.kms), Transport.transport).\
        filter(Transport.date > (datetime.now() - timedelta(days=5))).filter_by(author=current_user).\
        group_by(Transport.transport).order_by(Transport.transport.asc()).all()
    kms_transport = [0, 0, 0, 0, 0, 0]
    first_tuple_elements = []
    second_tuple_elements = []
    for a_tuple in kms_by_transport:
        first_tuple_elements.append(a_tuple[0])
        second_tuple_elements.append(a_tuple[1])
    if 'Bus' in second_tuple_elements:
        index_bus = second_tuple_elements.index('Bus')
        kms_transport[0] = first_tuple_elements[index_bus]
    if 'Car' in second_tuple_elements:
        index_car = second_tuple_elements.index('Car')
        kms_transport[1] = first_tuple_elements[index_car]
    if 'Ferry' in second_tuple_elements:
        index_ferry = second_tuple_elements.index('Ferry')
        kms_transport[2] = first_tuple_elements[index_ferry]
    if 'Plane' in second_tuple_elements:
        index_plane = second_tuple_elements.index('Plane')
        kms_transport[3] = first_tuple_elements[index_plane]
    if 'Train' in second_tuple_elements:
        index_train = second_tuple_elements.index('Train')
        kms_transport[4] = first_tuple_elements[index_train]
    if 'Walk' in second_tuple_elements:
        index_walk = second_tuple_elements.index('Walk')
        kms_transport[5] = first_tuple_elements[index_walk]
   
    # Kms by date (individual)
    kms_by_date = db.session.query(db.func.sum(Transport.kms), Transport.date).\
        filter(Transport.date > (datetime.now() - timedelta(days=5))).filter_by(author=current_user).\
        group_by(Transport.date).order_by(Transport.date.asc()).all()
    over_time_kms = []
    dates_label = []
    for total, date in kms_by_date:
        dates_label.append(date.strftime("%m-%d-%y"))
        over_time_kms.append(total)
    return render_template(
        'calculator/your_data.html',
        title='your_data',
        entries=entries,
        kms_by_transport=json.dumps(kms_transport),
        over_time_kms=json.dumps(over_time_kms),
        dates_label=json.dumps(dates_label)
    )
# Delete emission
@calculator.route('/calculator/delete-emission/<int:entry_id>')
def delete_emission(entry_id):
    entry = Transport.query.get_or_404(int(entry_id))
    db.session.delete(entry)
    db.session.commit()
    flash("Entry deleted", "success")
    return redirect(url_for('calculator.your_data'))

capp/templates/calculator/calculator_home.html
{% extends "layout.html" %}

{% block title %}Calculator{% endblock %}

{% block content %}



<!-- Section: Introduction text -->


    <div class="text-overlay">
        <h1>Our calculator</h1>

        <p>
           Hey, it’s me, Mr. Eco! <br><br>
           Let’s find out how your way of traveling affects the planet.
           Whether you drive, take the bus, hop on a train, or fly across the globe — 
           I’ll help you see how much CO₂ your trip produces.
           Just enter your distance and choose your transport mode, and I’ll do the rest.
           You might be surprised how small choices can make a big difference for our environment.
           <br><br>Ready to see your impact? Let’s explore together!
        </p>

        <div class="section_container_buttons_paper">
            <a class="btn_paper" href="{{url_for('static', filename='pdf/paper.pdf') }}" target="_blank">Our Paper</a>
        </div>
    </div>



<!-- Section: Boxes with means of transport -->

<div class="transport-grid">

    <a href="{{ url_for('calculator.new_entry_car') }}" class="transport-card">
        <i class="fa-solid fa-car-side"></i>
    </a>

    <a href="{{ url_for('calculator.new_entry_plane') }}" class="transport-card">
        <i class="fa-solid fa-plane"></i>
    </a>

    <a href="{{ url_for('calculator.new_entry_train') }}" class="transport-card">
        <i class="fa-solid fa-train-tram"></i>
    </a>

    <a href="{{ url_for('calculator.new_entry_ferry') }}" class="transport-card">
        <i class="fa-solid fa-ship"></i>
    </a>

    <a href="{{ url_for('calculator.new_entry_bus') }}" class="transport-card">
        <i class="fa-solid fa-bus"></i>
    </a>

    <a href="{{ url_for('calculator.new_entry_walk') }}" class="transport-card">
        <i class="fa-solid fa-person-walking"></i>
         <i class="fa-solid fa-bicycle"></i>
    </a>


{% endblock %}

capp/templates/calculator/new_entry_bus.html
{% extends "layout.html" %}
{% block content %}

<div class="calculator-grid">

  <!-- Calculator Card -->
  <div class="calculator-card">
    <p><strong>Bus Calculator</strong></p>
    <p>Please, enter the number of kilometers.</p>

    <form method="POST" action="">
      {{ form.csrf_token }}
      <fieldset class="form-group">

        <div class="form-group">
          {{ form.kms.label(class="form-control-label") }}
          {% if form.kms.errors %}
            {{ form.kms(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.kms.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.kms(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.fuel_type.label(class="form-control-label") }}
          {% if form.fuel_type.errors %}
            {{ form.fuel_type(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.fuel_type.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.fuel_type(class="form-control form-control-lg") }}
          {% endif %}
        </div>

      </fieldset>

      <div class="form-group mt-2">
        {{ form.submit(class="btn_carbon_app_new_entry_main") }}
      </div>
    </form>
  </div>

  <!-- Methodology Card -->
  <div class="calculator-card">
    <p><strong>Methodology</strong></p>
    <p>Buses carry many people at once, which keeps emissions per person low.  
       A typical diesel bus produces around <strong>30 g CO₂/pkm</strong>.</p>
    <p><strong>Tip from MR. Eco: Choosing public transport is one of the easiest ways to reduce your footprint without changing your routine!</strong></p>
  </div>

</div>

{% endblock %}

capp/templates/calculator/new_entry_car.html
{% extends "layout.html" %}
{% block content %}


<div class="calculator-grid">

  <!-- Calculator Card -->
  <div class="calculator-card">
    <p><strong>Car Calculator</strong></p>
    <p>1. Please, enter the number of kilometers.<br>
       2. Please, select the type of fuel.</p>

    <form method="POST" action="">
      {{ form.csrf_token }}
      <fieldset class="form-group">

        <div class="form-group">
          {{ form.kms.label(class="form-control-label") }}
          {% if form.kms.errors %}
            {{ form.kms(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.kms.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.kms(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.fuel_type.label(class="form-control-label") }}
          {% if form.fuel_type.errors %}
            {{ form.fuel_type(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.fuel_type.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.fuel_type(class="form-control form-control-lg") }}
          {% endif %}
        </div>

      </fieldset>

      <div class="form-group mt-2">
        {{ form.submit(class="btn_carbon_app_new_entry_main") }}
      </div>
    </form>
  </div>



 <!-- Methodology Card -->
  <div class="calculator-card">
    <p><strong>Methodology</strong></p>
    <p>The carbon footprint of your trip depends on your car’s fuel type. 
      A diesel car emits around <strong>229 g CO₂/pkm </strong>, while a petrol car produces about <strong>198g CO₂/pkm </strong>.
      An electric vehicle is the greenest choice with only <strong>59 g CO₂/pkm</strong> which is nearly 75% less than a diesel car.</strong>
    </p>
      <strong>Tip from MR. Eco: Sharing a ride makes it even greener!</strong>
    </p>
  </div>
</div>

{% endblock %}

capp/templates/calculator/new_entry_ferry.html
{% extends "layout.html" %}
{% block content %}

<div class="calculator-grid">

<!-- Calculator Card-->
  <div class="calculator-card">
    <p><strong>Ferry Calculator</strong></p>
    <p>1. Please, enter the number of kilometers.<br>
       2. Please, select transport mode.</p>

    <form method="POST" action="">
      {{ form.csrf_token }}
      <fieldset class="form-group">

        <div class="form-group">
          {{ form.kms.label(class="form-control-label") }}
          {% if form.kms.errors %}
            {{ form.kms(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.kms.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.kms(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.fuel_type.label(class="form-control-label") }}
          {% if form.fuel_type.errors %}
            {{ form.fuel_type(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.fuel_type.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.fuel_type(class="form-control form-control-lg") }}
          {% endif %}
        </div>

      </fieldset>

      <div class="form-group mt-2">
        {{ form.submit(class="btn_carbon_app_new_entry_main") }}
      </div>
    </form>
  </div>


<!-- Methodology Card-->
  <div class="calculator-card">
    <p><strong>Methodology</strong></p>
    <p>
      In Norway ferries are part of everyday life but the emissions depend on what you bring on board. 
      A passenger ferry produces about <strong>186 g CO₂/pkm</strong> while a car transported without passengers emits around <strong>377 g CO₂/pkm</strong>!
      </p> <strong>Tip from MR. Eco: Whenever possible, leave the car behind and enjoy the sea breeze. Your footprint will thank you! </strong>
  </p>
  </div>

</div>

{% endblock %}

capp/templates/calculator/new_entry_plane.html
{% extends "layout.html" %}
{% block content %}

<div class="calculator-grid">
<!-- Calculator Card -->
  <div class="calculator-card">
    <p><strong>Plane Calculator</strong></p>
    <p>1. Please, enter the number of kilometers.<br>
       2. Please, select the flight class.</p>

    <form method="POST" action="">
      {{ form.csrf_token }}
      <fieldset class="form-group">

        <div class="form-group">
          {{ form.kms.label(class="form-control-label") }}
          {% if form.kms.errors %}
            {{ form.kms(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.kms.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.kms(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.fuel_type.label(class="form-control-label") }}
          {% if form.fuel_type.errors %}
            {{ form.fuel_type(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.fuel_type.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.fuel_type(class="form-control form-control-lg") }}
          {% endif %}
        </div>

      </fieldset>

      <div class="form-group mt-2">
        {{ form.submit(class="btn_carbon_app_new_entry_main") }}
      </div>
    </form>
  </div>

  <!-- Methodology Card -->
  <div class="calculator-card">
    <p><strong>Methodology</strong></p>
    <p>
      Flying connects people and is sometimes the fastest way to travel but it also leaves a big footprint. 
      A flight in economy class produces about <strong>127 CO₂/pkm</strong> while business class can reach <strong>284 g CO₂/pkm</strong> since there’s more space per passenger. 
       </p><strong>Tip from MR. Eco: Choosing economy class or flying less often can make a big difference for the planet and your personal carbon footprint!</strong>
    </p>
  </div>

</div>

{% endblock %}

capp/templates/calculator/new_entry_train.html
{% extends "layout.html" %}
{% block content %}

<div class="calculator-grid">
<!-- Calculator Card -->
  <div class="calculator-card">
    <p><strong>Train Calculator</strong></p>
    <p>1. Please, enter the number of kilometers.<br>
       2. Please, select the type of fuel.</p>

    <form method="POST" action="">
      {{ form.csrf_token }}
      <fieldset class="form-group">

        <div class="form-group">
          {{ form.kms.label(class="form-control-label") }}
          {% if form.kms.errors %}
            {{ form.kms(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.kms.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.kms(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.fuel_type.label(class="form-control-label") }}
          {% if form.fuel_type.errors %}
            {{ form.fuel_type(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.fuel_type.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.fuel_type(class="form-control form-control-lg") }}
          {% endif %}
        </div>

      </fieldset>

      <div class="form-group mt-2">
        {{ form.submit(class="btn_carbon_app_new_entry_main") }}
      </div>
    </form>
  </div>


  <!-- Methodology Card -->
  <div class="calculator-card">
    <p><strong>Methodology</strong></p>
    <p>
      Trains are among the most climate friendly ways to travel. 
      An electric train emits only <strong>7 g CO₂/pkm </strong> while a diesel train produces around <strong>91 g CO₂/pkm</strong>. 
      </p> <strong>Tip from MR. Eco: Because many passengers share one journey trains are both efficient and comfortable. Every trip by train saves energy and emissions!</strong>
</p>
  </div>

</div>

{% endblock %}

capp/templates/calculator/new_entry_walk.html
{% extends "layout.html" %}
{% block content %}

<div class="calculator-grid">
<!-- Calculator Card -->
<div class="calculator-card">
    <p><strong>Walk/Bike Calculator</strong></p>
    <p>Please, enter the number of kilometers.</p>

    <form method="POST" action="">
      {{ form.csrf_token }}
      <fieldset class="form-group">

        <div class="form-group">
          {{ form.kms.label(class="form-control-label") }}
          {% if form.kms.errors %}
            {{ form.kms(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.kms.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.kms(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.fuel_type.label(class="form-control-label") }}
          {% if form.fuel_type.errors %}
            {{ form.fuel_type(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.fuel_type.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.fuel_type(class="form-control form-control-lg") }}
          {% endif %}
        </div>

      </fieldset>

      <div class="form-group mt-2">
        {{ form.submit(class="btn_carbon_app_new_entry_main") }}
      </div>
    </form>
  </div>


  <!-- Methodology Card -->
  <div class="calculator-card">
    <p><strong>Methodology</strong></p>
    <p>
     Zero emission, 100% freedom. 
    Walking and cycling produce obviously <strong>0 g CO₂/pkm</strong> and are the cleanest ways to move. 
     </p><strong> Tip from MR. Eco: They’re not only good for the planet but also for your health. Sometimes the greenest route is simply the one you take on your own two feet.</strong>
    </p>
  </div>

</div>

{% endblock %}

capp/templates/calculator/your_data.html
{% extends "layout.html" %}
{% block content %}

    <!-- New Entry Button -->
<br>
        <div class="container">
            <div class="box"> 
                <div class="btn_entry">
                    <a href="{{ url_for('calculator.calculator_home') }}" class="btn_entry">New Entry</a>
                </div>         
            </div>
        </div>
<br>

    <!-- Two Emissions Graph Section -->
    <section class="two_emissions_graphs">
        <div class="container">
            <div class="box">
                <canvas id="kms_by_transport"></canvas>
            </div>
            <div class="box">
                <canvas id="over_time_kms"></canvas>
            </div>
        </div>
    </section> 

    <!-- Table Section -->
    <section class="table_main">
    <div class="container">

        </div>
        <div class="box">  
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div> 
                    {% endfor %}
                {% endif %}
            {% endwith %}         
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">User</th>
                        <th scope="col">Date</th>
                        <th scope="col">Kilometres</th>
                        <th scope="col">Transport</th>
                        <th scope="col">Fuel/ Flight Class/Transport Class</th>
                        <th scope="col">Co2</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entry in entries %}
                        <tr>
                            <th scope="row">{{ current_user.username }}</th>
                            <td>{{ entry.date.strftime("%m-%d-%Y") }}</td>
                            <td>{{ entry.kms }}</td>
                            <td>{{ entry.transport }}</td>
                            <td>{{ entry.fuel }}</td>
                            <td>{{ entry.co2 }}</td>
                            <td><a href="{{ url_for('calculator.delete_emission', entry_id = entry.id) }}" class="btn btn-outline-danger btn-sm">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>       
        </div>
        <div class="box">
        </div>
    </div>
    </section> 


    <!-- Graph Section -->
{% block javascript %}
    <script>
   // Kilometers by type of transport --> Graph
        let kms_transport_data = JSON.parse({{ kms_by_transport | tojson }})    
        let kms_by_transport_chart = new Chart(kms_by_transport, {
                type: 'pie',
                data: {
                labels: ['Bus', 'Car', 'Ferry', 'Plane', 'Train', 'Walk'],
                    datasets: [{
                        label: "Income Vs Expenses",
                        data: kms_transport_data,
                        backgroundColor: ['#9ac2be', '#f2e3b6', '#f2c299',
                            '#f2935c', '#5fd9cd', '#f2d95c' ],    
                        borderWidth: 1,
                        hoverBorderColor: "black",
                        hoverBorderWidth: 2,
                        hoverBackgroundColor: 'rgba(154, 245, 140)',
                        pointHoverRadius: 5
                    }],
                },
                options: {
                        title: {
                            display: true,
                                text: "Kilometers by type of transport (5 last days)",
                                fontColor: "black",
                                fontSize: 20,
                        },
                        legend: {
                            position: "right",
                                labels: {
                                fontColor: "black"
                            },
                            display: true,
                        },
    
                        elements: {
                            hitRadius: 3,
                        }
                }
            })
            
        over_time_kms = JSON.parse({{over_time_kms | tojson}})
        labels = JSON.parse({{ dates_label  | tojson}})

        new Chart(document.getElementById("over_time_kms"), {
                type: "line",
                data:
                {
                    labels: labels,
                    datasets: [
                        {
                        label: "Individual Kilometers (5 past days)",                            
                        data: over_time_kms,
                        fill: false,
                        borderColor: '#f2d95c',
                        lineTension: 0.1
                        }
                ]
                },                    
                options: {}
            });   

        </script>

{% endblock %}
{% endblock %}
