capp/aboutus/__init__.py
#

capp/aboutus/routes.py
from flask import render_template, Blueprint

aboutus=Blueprint('aboutus',__name__)

@aboutus.route('/aboutus')
def aboutus_home():
  return render_template('aboutus.html', title='aboutus')

capp/calculator/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, flash
from capp.models import Transport
from capp import db
from datetime import timedelta, datetime
from flask_login import login_required, current_user
from capp.calculator.forms import BusForm, CarForm, PlaneForm, FerryForm, TrainForm, WalkForm
import json
calculator = Blueprint('calculator', __name__)
# Emissions factor per transport in kg per passenger km
# Data from: 
efco2 = {
    'Bus': {'Diesel': 0.030},
    'Car': {'Petrol': 0.198, 'Diesel': 0.229, 'Electric': 0.059},
    'Plane': {'Economy': 0.127, 'Business': 0.284},
    'Ferry': {'Passenger with car': 0.563, 'Passenger only': 0.186},
    'Train': {'Diesel': 0.091, 'Electric': 0.007},
    'Walk': {'No Fossil Fuel': 0}
}
# Carbon app, main page
@calculator.route('/calculator')
@login_required
def calculator_home():
    return render_template('calculator/calculator_home.html', title='calculator')
# Carbon app, plane
@calculator.route('/calculator/new_entry_plane', methods=['GET', 'POST'])
@login_required
def new_entry_plane():
    form = PlaneForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Plane'
        co2 = float(kms) * efco2[transport][fuel]
        co2 = float("{:.2f}".format(co2))
        emissions = Transport(
            kms=kms,
            transport=transport,
            fuel=fuel,
            co2=co2,
            author=current_user
        )
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template(
        'calculator/new_entry_plane.html',
        title='Plane Calculator',
        form=form
    )
# Carbon app, walk
@calculator.route('/calculator/new_entry_walk', methods=['GET', 'POST'])
@login_required
def new_entry_walk():
    form = WalkForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Walk'
        co2 = float(kms) * efco2[transport][fuel]
        co2 = float("{:.2f}".format(co2))
        emissions = Transport(
            kms=kms,
            transport=transport,
            fuel=fuel,
            co2=co2,
            author=current_user
        )
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template(
        'calculator/new_entry_walk.html',
        title='Walk/Bike Calculator',
        form=form
    )
# Carbon app, bus
@calculator.route('/calculator/new_entry_bus', methods=['GET', 'POST'])
@login_required
def new_entry_bus():
    form = BusForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Bus'
        co2 = float(kms) * efco2[transport][fuel]
        co2 = float("{:.2f}".format(co2))
        emissions = Transport(
            kms=kms,
            transport=transport,
            fuel=fuel,
            co2=co2,
            author=current_user
        )
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template(
        'calculator/new_entry_bus.html',
        title='Bus Calculator',
        form=form
    )
# Carbon app, car
@calculator.route('/calculator/new_entry_car', methods=['GET', 'POST'])
@login_required
def new_entry_car():
    form = CarForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Car'
        co2 = float(kms) * efco2[transport][fuel]
        co2 = float("{:.2f}".format(co2))
        emissions = Transport(
            kms=kms,
            transport=transport,
            fuel=fuel,
            co2=co2,
            author=current_user
        )
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template(
        'calculator/new_entry_car.html',
        title='Car Calculator',
        form=form
    )
# Carbon app, ferry
@calculator.route('/calculator/new_entry_ferry', methods=['GET', 'POST'])
@login_required
def new_entry_ferry():
    form = FerryForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Ferry'
        co2 = float(kms) * efco2[transport][fuel]
        co2 = float("{:.2f}".format(co2))
        emissions = Transport(
            kms=kms,
            transport=transport,
            fuel=fuel,
            co2=co2,
            author=current_user
        )
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template(
        'calculator/new_entry_ferry.html',
        title='Ferry Calculator',
        form=form
    )
# Carbon app, train
@calculator.route('/calculator/new_entry_train', methods=['GET', 'POST'])
@login_required
def new_entry_train():
    form = TrainForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Train'
        co2 = float(kms) * efco2[transport][fuel]
        co2 = float("{:.2f}".format(co2))
        emissions = Transport(
            kms=kms,
            transport=transport,
            fuel=fuel,
            co2=co2,
            author=current_user
        )
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template(
        'calculator/new_entry_train.html',
        title='Train Calculator',
        form=form
    )
# Your data
@calculator.route('/calculator/your_data')
@login_required
def your_data():
    # Table
    entries = Transport.query.filter_by(author=current_user).\
        filter(Transport.date > (datetime.now() - timedelta(days=5))).\
        order_by(Transport.date.desc()).order_by(Transport.transport.asc()).all()
    
    # Kilometers by category
    kms_by_transport = db.session.query(db.func.sum(Transport.kms), Transport.transport).\
        filter(Transport.date > (datetime.now() - timedelta(days=5))).filter_by(author=current_user).\
        group_by(Transport.transport).order_by(Transport.transport.asc()).all()
    kms_transport = [0, 0, 0, 0, 0, 0]
    first_tuple_elements = []
    second_tuple_elements = []
    for a_tuple in kms_by_transport:
        first_tuple_elements.append(a_tuple[0])
        second_tuple_elements.append(a_tuple[1])
    if 'Bus' in second_tuple_elements:
        index_bus = second_tuple_elements.index('Bus')
        kms_transport[0] = first_tuple_elements[index_bus]
    if 'Car' in second_tuple_elements:
        index_car = second_tuple_elements.index('Car')
        kms_transport[1] = first_tuple_elements[index_car]
    if 'Ferry' in second_tuple_elements:
        index_ferry = second_tuple_elements.index('Ferry')
        kms_transport[2] = first_tuple_elements[index_ferry]
    if 'Plane' in second_tuple_elements:
        index_plane = second_tuple_elements.index('Plane')
        kms_transport[3] = first_tuple_elements[index_plane]
    if 'Train' in second_tuple_elements:
        index_train = second_tuple_elements.index('Train')
        kms_transport[4] = first_tuple_elements[index_train]
    if 'Walk' in second_tuple_elements:
        index_walk = second_tuple_elements.index('Walk')
        kms_transport[5] = first_tuple_elements[index_walk]
   
    # Kms by date (individual)
    kms_by_date = db.session.query(db.func.sum(Transport.kms), Transport.date).\
        filter(Transport.date > (datetime.now() - timedelta(days=5))).filter_by(author=current_user).\
        group_by(Transport.date).order_by(Transport.date.asc()).all()
    over_time_kms = []
    dates_label = []
    for total, date in kms_by_date:
        dates_label.append(date.strftime("%m-%d-%y"))
        over_time_kms.append(total)
    return render_template(
        'calculator/your_data.html',
        title='your_data',
        entries=entries,
        kms_by_transport=json.dumps(kms_transport),
        over_time_kms=json.dumps(over_time_kms),
        dates_label=json.dumps(dates_label)
    )
# Delete emission
@calculator.route('/calculator/delete-emission/<int:entry_id>')
def delete_emission(entry_id):
    entry = Transport.query.get_or_404(int(entry_id))
    db.session.delete(entry)
    db.session.commit()
    flash("Entry deleted", "success")
    return redirect(url_for('calculator.your_data'))

capp/home/__init__.py
#

capp/home/routes.py
from flask import render_template, Blueprint

home=Blueprint('home',__name__)

@home.route('/')
@home.route('/home')
def home_home():
  return render_template('home.html')

capp/users/routes.py
from flask import render_template, Blueprint, redirect, flash, url_for, request
from capp.users.forms import RegistrationForm, LoginForm
from capp.models import User
from capp import db, bcrypt
from flask_login import login_user, current_user, logout_user

users=Blueprint('users',__name__)

@users.route('/register', methods=['GET','POST'])
def register():
  form = RegistrationForm()
  if current_user.is_authenticated:
        return redirect(url_for('home.home_home'))
  if form.validate_on_submit():
      user_hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      user = User(username=form.username.data, email=form.email.data, password=user_hashed_password)
      db.session.add(user)
      db.session.commit()
      flash('Your account has been created! Now, you are able to login!', 'success')
      return redirect(url_for('users.login'))
  return render_template('users/register.html', title='register', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
  form = LoginForm()
  if current_user.is_authenticated:
        return redirect(url_for('home.home_home'))
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
        login_user(user, remember=form.remember.data)
        next_page = request.args.get('next')
        flash('You have logged in! Now, you can start to use our Carbon App!', 'success')
        return redirect(next_page) if next_page else redirect(url_for('home.home_home'))
    else:
        flash('Login Unsuccessful. Please check email and password!', 'danger') 
  return render_template('users/login.html', title='login', form=form)

@users.route('/logout')
def logout():    
    logout_user()
    return redirect(url_for('home.home_home'))


capp/templates/aboutus.html
{% extends "layout.html" %}
{% block content %}

<!-- Section: Presentation of the Team (Picture in background) -->

<section class="picture">
    <div class="text-overlay">
      <h1> About Us</h1>
      </p> 
        We are two students united by a shared passion for tackling climate change. Bringing our own perspectives and ideas, we wanted to create something meaningful that makes environmental impact visible and understandable. With MR. Eco as our guide, we turn sustainable choices into a fun, engaging, and playful journey toward a greener future.
      </p>
    </div>

</section>

<!-- Team members-->

<section class="team-section">
  <div class="team-grid">

    <div class="team-card">
      <img src="{{ url_for('static', filename='images/julie.jpeg') }}"  alt="" style="border-radius: 50%; width:150px;">
      <h3>Julie Joan</h3>
      <p>Hi, I’m Julie, and I’m currently pursuing a Master’s degree in Digital Education for Sustainable Development at Heidelberg University of Education. In my studies, I explore the intersections of education, digitalization, and sustainability. I’m particularly interested in how digital media and innovative approaches can be used to foster a more sustainable future.
      </p>
      <div class="section_container_buttons_linkedin">
        <a class="btn_linkedin" href="https://www.linkedin.com/in/julie-joan-ab2b98326/"  target="_blank">LinkedIn</a>
      </div> 
    </div>    

  <div class="team-card">
    <img src="{{ url_for('static', filename='images/shaira.jpeg') }}"  alt="" style="border-radius: 50%; width:150px;">
    <h3> Shaira Krüglstein</h3>
    <p>My name is Shaira, I come from Germany and I study Human Resources Management. I enjoy working with people and learning what motivates them, and that is also why sustainability interests me. I believe that even small actions can make a difference, and I like being part of projects that create awareness and positive change.
    </p>
    <div class="section_container_buttons_linkedin">
        <a class="btn_linkedin" href="https://www.linkedin.com/in/shaira-kr%C3%BCglstein-8b0107214/"  target="_blank">LinkedIn</a>
    </div> 
  </div>

</div>          
</section>


{% endblock content %}

capp/templates/home.html
{% extends "layout.html" %}
{% block content %}


<!-- Background picture -->
<section class="homepagebackground"
  style="
    background-image: url('{{ url_for('static', filename='images/trolltunganight.jpeg') }}');
    ">
<!-- Textbox -->
  <div class="text-overlay">

    <h1 style="font-size:55px;">
      Hi there!
    </h1>

    <p>
       Welcome to Mr. Eco where awareness meets action. Every day, we travel from one place to another: to work, to school, to see friends.
       But have you ever thought about how those journeys affect the planet? Even small trips add up, and understanding their impact is the first step toward change.
       That’s where Mr. Eco comes in, your friendly carbon detective.
       He helps you uncover the emissions behind your daily travel, turning data into stories and awareness into action.
       With just a few taps, you can see how your choices shape your footprint and how simple changes can make a real difference.
       Because saving the planet shouldn’t feel like homework it should feel like progress.
       So, are you ready to see your travels in a new way?
      </p>
    
      <a class="btn_investigate" href="{{ url_for('calculator.calculator_home') }}" >
      Let's investigate!
      </a>
    </div>
  </div>

</section>


{% endblock %}

capp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" 
       integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" 
    crossorigin="anonymous" 
    referrerpolicy="no-referrer"/>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous"/>

    <!-- CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='layout.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='aboutus.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='calculator.css') }}">


    <meta name="viewport" content="user-scalable=yes, width=device-width, initial-scale=1">
    <title>{% block title %}Default Title{% endblock %}</title>

       

</head>


   <!--For the plots-->
      <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
      <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> -->

<!-- Navbar-->

<body>
  <section class="section_navbar">
    <div class="navbar">
      <div class="logo">
      <span class="text-logo"><i class="fa-solid fa-user-secret"></i></span>
      <span class="logo-text">MR. EC</span>
      <span class="text-logo-o"><i class="fa-solid fa-magnifying-glass"></i></span>
    </div>
        {% if current_user.is_authenticated %}
    <nav>
      <ul>
        <li><a href="{{ url_for('home.home_home') }}">Home</a></li>
        <li><a href="{{ url_for('calculator.calculator_home') }}">Calculator</a></li>
        <li><a href="{{ url_for('calculator.your_data') }}">Your data</a></li>
        <li><a href="{{ url_for('aboutus.aboutus_home') }}">About Us</a></li>
        <li><a href="{{url_for('users.logout')}}">Logout</a> </li>
      </ul>
    </nav>

          {% else %}
  <nav>
      <ul>
        <li><a href="{{ url_for('home.home_home') }}">Home</a></li>
        <li><a href="{{ url_for('calculator.calculator_home') }}">Calculator</a></li>
        <li><a href="{{ url_for('aboutus.aboutus_home') }}">About Us</a></li>
        <li><a href="{{url_for('users.login')}}">Login</a> </li>
        <li> <a href="{{url_for('users.register')}}">Register</a> </li>
      </ul>
    </nav>
    {% endif %}
     </div>
  </div>
</section>


<!-- Body of the webside-->
<main>
    {% block content %}
    {% endblock %}
</main>

<!-- Footer-->
<section class="section_footer">
  <div class="footer">
  <div class="logo">
      <span class="logo-text">MR. EC</span>
      <span class="text-logo-o"><i class="fa-solid fa-magnifying-glass"></i></span>
        <a href="#">
                  <i class="fa-solid fa-circle-up" style="color: #568c63"></i>
                </a>
    </div>
  </div>
</section>